apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: gateway-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  storageClassName: nfs-client
